Fix for netaddr v1.3.0 upgrade and pep8 error
It is necessary to specify "expand_partial=True" in IPNetwork init
to expand partial addresses from netaddr v1.3.0.
This patch fixes it so that "expand_partial" can be specified
in IPNetwork init.

And bump the hacking version to 7.0.0 and fix the pep8
error:
 - AttributeError: 'EntryPoints' object has no attribute 'get'

Closes-Bug: #2089815
Closes-Bug: #2088356
Change-Id: I2deb71242f555bbae5ee7c798add18490cb38344